# -*- coding: utf-8 -*-
"""Configuration templates for social network topologies."""

# Topology type definitions - parameters will be generated by LLM
TOPOLOGY_DEFINITIONS = {
    'random': {
        'name': 'Random Network',
        'description': 'Agents connect randomly with probability determined by scenario context',
        'use_cases': ['loose social connections', 'general social networks', 'acquaintance networks'],
        'llm_params': ['connection_probability']
    },
    
    'grid': {
        'name': 'Spatial Grid',
        'description': 'Agents arranged in N×N grid, connecting only to adjacent neighbors',
        'use_cases': ['spatial simulations', 'geographical constraints', 'neighborhood interactions', 'disease spread'],
        'llm_params': ['dimensions', 'boundary_type', 'diagonal_connections']
    },
    
    'complete': {
        'name': 'Complete Graph',
        'description': 'Every agent connects to every other agent',
        'use_cases': ['small groups', 'workshops', 'meetings', 'tight communities'],
        'llm_params': []
    },
    
    'star': {
        'name': 'Star Topology',
        'description': 'One central agent connects to all others',
        'use_cases': ['authority structures', 'central hub scenarios', 'broadcast networks'],
        'llm_params': ['central_agent']
    },
    
    'hierarchical': {
        'name': 'Hierarchical Tree',
        'description': 'Tree-like structure with parent-child relationships',
        'use_cases': ['organizational hierarchies', 'command structures', 'family trees'],
        'llm_params': ['branching_factor']
    }
}


def get_topology_info(topology_name: str) -> dict:
    """Get information about a topology type.
    
    Args:
        topology_name: Name of the topology
        
    Returns:
        Information dictionary or None if not found
    """
    return TOPOLOGY_DEFINITIONS.get(topology_name)


def get_available_topologies() -> list:
    """Get list of available topology names."""
    return list(TOPOLOGY_DEFINITIONS.keys())


def get_topology_descriptions() -> dict:
    """Get dictionary of topology names and their descriptions."""
    return {name: info['description'] for name, info in TOPOLOGY_DEFINITIONS.items()}


def get_topology_use_cases() -> dict:
    """Get dictionary of topology names and their use cases."""
    return {name: info['use_cases'] for name, info in TOPOLOGY_DEFINITIONS.items()}