[project]
name = "fabscore"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "transformers",
    "openai>=2.14.0",
    "pandas",
    "numpy>=2.4.2",
    "tqdm",
    "matplotlib",
    "seaborn",
    "datasets",
    "anthropic>=0.75.0",
    "scikit-learn",
    "nltk",
    "wandb",
    "gpustat",
    "google>=3.0.0",
    "google-genai>=1.43.0",
    "dotenv",
    "docling",
    "torch",
    "torchvision",
    "einops",
    "pypdf2>=3.0.1",
    "pypdf>=6.10.0",
    "plotly>=6.7.0",
    "litellm>=1.83.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
