import os
import os.path as osp
import re
import json
import time
import logging
from logging import Logger
from pathlib import Path
import base64
from typing import Any, Callable, Dict, Optional, List
from PIL import Image

SUPPORTED_JUDGES = ("claude", "codex", "gemini")


def _get_file_structure(task_path: str, max_depth: int = 4) -> str:
    lines: List[str] = []
    start_level = task_path.rstrip(os.sep).count(os.sep)
    for root, dirs, files in os.walk(task_path):
        level = root.count(os.sep) - start_level
        if level > max_depth:
            continue
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        indent = "  " * level
        lines.append(f"{indent}{osp.basename(root)}/")
        subindent = "  " * (level + 1)
        for name in sorted(files):
            if name.endswith((".py", ".sh", ".md", ".txt", ".json", ".yaml", ".yml", ".toml")):
                lines.append(f"{subindent}{name}")
    return "\n".join(lines)


def _get_bucket_items(data: Dict, bucket: str) -> List[Dict]:
    bucket_items = data.get(bucket, [])
    if isinstance(bucket_items, list):
        return bucket_items
    return []

def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")


def _clean_markdown(md_text: str, converted_dir: str) -> str:
    """
    Post-process converted Markdown text.
    """
    # 1a. Remove standalone line numbers
    md_text = re.sub(r'\n\d{3}\n', '\n', md_text)
    md_text = re.sub(r'^\d{3}\n', '', md_text)

    # 1b. Remove crammed line number sequences
    md_text = re.sub(r'(?:^|\n)(\d{3}\s+){4,}', '\n', md_text)

    # 1c. Remove repeated watermark fragments commonly injected into AI Scientist PDFs.
    watermark_phrases = [
        r'CAUTION!!!\s*THIS PAPER WAS\s*AUTONOMOUSLY GENERATED BY THE AI SCIENTIST',
        r'CAUTION!!!\s*AUTONOMOUSLY GENERATED BY THE AI SCIENTIST',
        r'THIS PAPER WAS\s*AUTONOMOUSLY GENERATED BY THE AI SCIENTIST',
        r'AUTONOMOUSLY GENERATED BY THE AI SCIENTIST',
    ]
    for phrase in watermark_phrases:
        md_text = re.sub(phrase, '', md_text, flags=re.IGNORECASE)

    # Remove leftover watermark shards that Docling sometimes emits as isolated lines.
    md_text = re.sub(
        r'(?im)^\s*(?:CAUTION!!!|THIS PAPER WAS|AUTONOMOUSLY GENERATED)\s*$\n?',
        '',
        md_text,
    )

    # Normalize extra whitespace created by watermark removal.
    md_text = re.sub(r'[ \t]{2,}', ' ', md_text)
    md_text = re.sub(r' *\n *', '\n', md_text)

    # 2. Convert absolute image paths to relative
    if converted_dir:
        abs_prefix = converted_dir.rstrip("/") + "/"
        md_text = md_text.replace(abs_prefix, "")

    # 3. Collapse excessive blank lines
    md_text = re.sub(r'\n{3,}', '\n\n', md_text)

    return md_text


def convert_pdf_to_markdown(pdf_path: str, task_path: str) -> str:
    """
    Convert a PDF file to Markdown using Docling, with images extracted.
    """
    try:
        from docling.document_converter import DocumentConverter, PdfFormatOption
        from docling.datamodel.base_models import InputFormat
        from docling.datamodel.pipeline_options import PdfPipelineOptions
        from docling_core.types.doc import ImageRefMode, PictureItem
    except ImportError as exc:
        raise RuntimeError(
            "PDF conversion requires the optional 'docling' dependency. "
            "Install docling or provide a Markdown paper path instead."
        ) from exc

    converted_dir = Path(task_path) / "converted_markdown"
    image_dir = converted_dir / "images"
    image_dir.mkdir(parents=True, exist_ok=True)

    md_path = converted_dir / "paper.md"

    if md_path.is_file():
        logging.info(f"Converted Markdown already exists: {md_path}, skipping conversion.")
        return osp.relpath(str(md_path), task_path)

    logging.info(f"Converting PDF to Markdown with Docling: {pdf_path}")

    for logger_name in ("docling", "docling_core", "docling_ibm_models", "docling_parse"):
        logging.getLogger(logger_name).setLevel(logging.WARNING)

    pipeline_options = PdfPipelineOptions()
    pipeline_options.images_scale = 4.0
    pipeline_options.generate_picture_images = True

    doc_converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
        }
    )
    conv_res = doc_converter.convert(pdf_path)
    doc = conv_res.document

    doc.save_as_markdown(
        md_path,
        image_mode=ImageRefMode.REFERENCED,
        artifacts_dir=image_dir,
    )

    picture_counter = sum(
        1 for element, _ in doc.iterate_items()
        if isinstance(element, PictureItem)
    )

    md_text = md_path.read_text(encoding="utf-8")
    md_text = _clean_markdown(md_text, str(converted_dir))
    md_path.write_text(md_text, encoding="utf-8")

    logging.info(f"PDF converted to Markdown: {md_path} ({picture_counter} figures extracted)")
    return osp.relpath(str(md_path), task_path)
