agent:
  code:
    max_tokens: 28000
    model: gpt-5-2025-08-07
    temp: 1.0
  data_preview: false
  expose_prediction: false
  feedback:
    max_tokens: 8192
    model: gpt-5-2025-08-07
    temp: 1.0
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 3
  num_workers: 3
  search:
    debug_prob: 0.5
    max_debug_depth: 3
    num_drafts: 3
  stages:
    stage1_max_iters: 15
    stage2_max_iters: 9
    stage3_max_iters: 9
    stage4_max_iters: 12
  steps: 5
  type: parallel
  vlm_feedback:
    max_tokens: null
    model: gpt-4o-2024-08-06
    temp: 0.7
copy_data: true
data_dir: experiments/2025-09-13_11-32-42_resource_centric_ppm_agents_attempt_0/data
debug:
  stage4: false
desc_file: experiments/2025-09-13_11-32-42_resource_centric_ppm_agents_attempt_0/idea.json
eval: null
exec:
  agent_file_name: runfile.py
  format_tb_ipython: false
  timeout: 3600
exp_name: run
experiment:
  num_syn_datasets: 0
generate_report: true
goal: null
log_dir: experiments/2025-09-13_11-32-42_resource_centric_ppm_agents_attempt_0/logs
preprocess_data: false
report:
  model: gpt-5-2025-08-07
  temp: 1.0
workspace_dir: experiments/2025-09-13_11-32-42_resource_centric_ppm_agents_attempt_0
