"""Coupling diagnostic: check-performance vs main-question performance for B and C.

In V3 verified-facts mode, checks are provided as correct demonstrations in the
prompt (not generated by the model). Since checks are always correct by
construction, the standard coupling metric (P[main|all checks ok] vs
P[main|any check wrong]) is degenerate: all items have all_checks_correct.

We report:
1. The degenerate prompt-level coupling (all items -> all_checks_correct bucket)
2. The effective coupling gap: accuracy difference C - B, interpreted as the
   additional binding provided by discriminative vs neutral checks
3. Per-family breakdown of the effective coupling
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from dut_project.evaluation.coupling import compute_coupling
from dut_project.evaluation.score import score_item
from dut_project.inference.parse_outputs import (
    _normalize_answer,
    extract_answer_robust,
    parse_output,
)


PROJ = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BENCH_PATH = os.path.join(PROJ, "dut_project/data/erdos_conventions_bench.jsonl")

MODEL_CONFIGS = {
    "Qwen2.5-Math-7B": {
        "output_dir": os.path.join(PROJ, "dut_project/outputs/qwen25_math_7b_v3"),
        "use_robust_extract": False,
    },
    "Llama-3.1-8B": {
        "output_dir": os.path.join(PROJ, "dut_project/outputs/llama31_8b"),
        "use_robust_extract": True,
    },
}


def load_jsonl(path):
    with open(path) as f:
        return [json.loads(line) for line in f]


def extract_final_answer_robust(raw_output, parsed_final, family=None):
    text = raw_output.strip()
    if not text:
        return None
    boxed = re.findall(r"\\boxed\{([^}]+)\}", text)
    if boxed:
        ans = boxed[-1].strip()
        ans = re.sub(r"^\\text\{", "", ans)
        ans = ans.rstrip("}")
        return _normalize_answer(ans)
    if parsed_final is not None:
        return _normalize_answer(parsed_final)
    return None


def score_outputs(outputs, bench_map, condition, use_robust):
    scored_items = []
    for out in outputs:
        item = bench_map[out["item_id"]]
        raw = out["raw_output"]
        family = out["family"]

        if use_robust:
            ans = extract_answer_robust(raw, family=family)
            gt = _normalize_answer(item["ground_truth_glossary"])
            main_correct = (ans == gt) if ans else False
            predicted = ans
        else:
            reparsed = parse_output(raw, k=3)
            final = extract_final_answer_robust(raw, reparsed["final_answer"], family)
            gt = _normalize_answer(item["ground_truth_glossary"])
            main_correct = (_normalize_answer(final) == gt) if final else False
            predicted = final

        checks_key = "neutral_checks" if condition == "B" else "discriminative_checks"
        gt_checks = item[checks_key]
        check_results = []
        for i in range(min(3, len(gt_checks))):
            check_results.append({
                "check_idx": i,
                "predicted": gt_checks[i]["answer_glossary"],
                "ground_truth": gt_checks[i]["answer_glossary"],
                "correct": True,
            })

        scored_items.append({
            "item_id": out["item_id"],
            "family": family,
            "condition": condition,
            "main_correct": main_correct,
            "predicted_answer": predicted,
            "ground_truth": item["ground_truth_glossary"],
            "check_results": check_results,
        })
    return scored_items


def compute_per_family_accuracy(scored_items):
    families = sorted(set(s["family"] for s in scored_items))
    per_family = {}
    for fam in families:
        fam_items = [s for s in scored_items if s["family"] == fam]
        n_correct = sum(1 for s in fam_items if s["main_correct"])
        per_family[fam] = {
            "accuracy": n_correct / len(fam_items) if fam_items else 0,
            "correct": n_correct,
            "total": len(fam_items),
        }
    return per_family


def plot_coupling_diagnostic(results, output_path):
    models = list(results.keys())
    conditions = ["B", "C"]
    bar_types = ["all_checks_correct"]

    colors_b = {"all_checks_correct": "#6baed6"}
    colors_c = {"all_checks_correct": "#fd8d3c"}

    fig, axes = plt.subplots(1, len(models), figsize=(10, 5), sharey=True)
    if len(models) == 1:
        axes = [axes]

    for ax, model in zip(axes, models):
        x = np.arange(2)
        width = 0.6

        vals = []
        labels = []
        colors = []
        for cond in conditions:
            coupling = results[model][cond]["prompt_level_coupling"]
            p = coupling["p_main_correct_given_all_checks_correct"]
            vals.append(p if p is not None else 0)
            n = coupling["n_all_checks_correct"]
            labels.append(f"Cond {cond}\n(n={n})")
            colors.append("#6baed6" if cond == "B" else "#fd8d3c")

        bars = ax.bar(x, vals, width, color=colors, edgecolor="black")
        for bar, val in zip(bars, vals):
            if val > 0:
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.01,
                    f"{val:.1%}",
                    ha="center", va="bottom", fontsize=11, fontweight="bold",
                )

        ax.set_xticks(x)
        ax.set_xticklabels(labels, fontsize=10)
        ax.set_ylabel("P[main correct | all checks correct]" if ax == axes[0] else "")
        ax.set_title(model, fontsize=12, fontweight="bold")
        ax.set_ylim(0, 1.15)
        ax.axhline(y=1.0, color="gray", linestyle="--", alpha=0.3)

        gap = vals[1] - vals[0]
        ax.annotate(
            f"C - B = {gap:+.1%}",
            xy=(0.5, max(vals) + 0.06),
            fontsize=10,
            ha="center",
            fontweight="bold",
            color="darkred",
        )

    fig.suptitle(
        "Coupling Diagnostic: P[main correct | all checks correct]\n"
        "(V3 verified-facts: all checks correct by construction)",
        fontsize=12, fontweight="bold",
    )
    fig.tight_layout()
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved coupling diagnostic plot to {output_path}")


def plot_per_family_coupling_table(results, output_path):
    models = list(results.keys())
    families = ["asymptotics", "completeness", "convolution"]

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axis("off")

    headers = ["Model", "Family", "Acc B", "Acc C", "Gap (C-B)", "Stronger\nCoupling?"]
    rows = []
    for model in models:
        b_fam = results[model]["B"]["per_family"]
        c_fam = results[model]["C"]["per_family"]
        for fam in families:
            acc_b = b_fam.get(fam, {}).get("accuracy", 0)
            acc_c = c_fam.get(fam, {}).get("accuracy", 0)
            gap = acc_c - acc_b
            stronger = "Yes" if gap > 0.05 else ("Marginal" if gap > 0 else "No")
            rows.append([
                model, fam.capitalize(),
                f"{acc_b:.1%}", f"{acc_c:.1%}",
                f"{gap:+.1%}", stronger,
            ])

    table = ax.table(
        cellText=rows,
        colLabels=headers,
        loc="center",
        cellLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 1.5)

    for (r, c), cell in table.get_celld().items():
        if r == 0:
            cell.set_facecolor("#4472C4")
            cell.set_text_props(color="white", fontweight="bold")
        elif r % 3 == 0:
            cell.set_facecolor("#f0f0f0")

        if r > 0 and c == 5:
            text = cell.get_text().get_text()
            if text == "Yes":
                cell.set_facecolor("#c6efce")
            elif text == "Marginal":
                cell.set_facecolor("#ffeb9c")
            elif text == "No":
                cell.set_facecolor("#ffc7ce")

    fig.suptitle(
        "Per-Family Coupling: Accuracy Under B vs C",
        fontsize=12, fontweight="bold",
    )
    fig.tight_layout()
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved per-family coupling table to {output_path}")


def main():
    bench_items = load_jsonl(BENCH_PATH)
    bench_map = {it["item_id"]: it for it in bench_items}

    all_results = {}

    for model_name, cfg in MODEL_CONFIGS.items():
        print(f"\n{'='*60}")
        print(f"Model: {model_name}")
        print(f"{'='*60}")

        model_results = {}
        for cond in ["B", "C"]:
            path = os.path.join(cfg["output_dir"], f"condition_{cond.lower()}.jsonl")
            outputs = load_jsonl(path)
            scored = score_outputs(outputs, bench_map, cond, cfg["use_robust_extract"])

            n_correct = sum(1 for s in scored if s["main_correct"])
            overall_acc = n_correct / len(scored)
            print(f"\n  Condition {cond}: {n_correct}/{len(scored)} = {overall_acc*100:.1f}%")

            prompt_coupling = compute_coupling(scored)
            print(f"  Prompt-level coupling:")
            print(f"    n_all_checks_correct = {prompt_coupling['n_all_checks_correct']}")
            print(f"    n_any_check_wrong = {prompt_coupling['n_any_check_wrong']}")
            print(f"    P[main|all checks ok] = {prompt_coupling['p_main_correct_given_all_checks_correct']}")
            print(f"    P[main|any check wrong] = {prompt_coupling['p_main_correct_given_any_check_wrong']}")
            print(f"    coupling_gap = {prompt_coupling['coupling_gap']}")

            per_family = compute_per_family_accuracy(scored)
            print(f"  Per-family accuracy:")
            for fam, fd in per_family.items():
                print(f"    {fam}: {fd['accuracy']:.1%} ({fd['correct']}/{fd['total']})")

            model_results[cond] = {
                "overall_accuracy": overall_acc,
                "n_correct": n_correct,
                "n_total": len(scored),
                "prompt_level_coupling": prompt_coupling,
                "per_family": per_family,
            }

        all_results[model_name] = model_results

    comparison = {}
    for model_name in all_results:
        b = all_results[model_name]["B"]
        c = all_results[model_name]["C"]
        acc_gap = c["overall_accuracy"] - b["overall_accuracy"]

        per_family_gaps = {}
        families = sorted(set(b["per_family"].keys()) | set(c["per_family"].keys()))
        for fam in families:
            b_acc = b["per_family"].get(fam, {}).get("accuracy", 0)
            c_acc = c["per_family"].get(fam, {}).get("accuracy", 0)
            per_family_gaps[fam] = {
                "accuracy_B": b_acc,
                "accuracy_C": c_acc,
                "gap_C_minus_B": c_acc - b_acc,
                "discriminative_checks_stronger": (c_acc - b_acc) > 0,
            }

        comparison[model_name] = {
            "accuracy_B": b["overall_accuracy"],
            "accuracy_C": c["overall_accuracy"],
            "effective_coupling_gap": acc_gap,
            "per_family_gaps": per_family_gaps,
            "interpretation": (
                "In V3 verified-facts mode, all checks are correct by construction. "
                "The effective coupling gap (C-B accuracy difference) measures how much "
                "discriminative checks improve main accuracy beyond neutral checks. "
                f"Gap = {acc_gap:+.1%}. "
                + ("Discriminative checks show stronger coupling." if acc_gap > 0.02
                   else "No significant coupling difference.")
            ),
        }

    output = {
        "description": (
            "Coupling diagnostic between check performance and main-question performance. "
            "In V3 verified-facts mode, checks are provided as correct demonstrations in "
            "the prompt (not generated by the model). Therefore P[main correct | all checks "
            "correct] = overall accuracy for all items, and P[main correct | any check wrong] "
            "is undefined (no items in this bucket). The effective coupling is measured as the "
            "accuracy improvement from neutral checks (B) to discriminative checks (C)."
        ),
        "v3_mode_note": (
            "All checks are correct by construction in V3 mode. The standard coupling gap "
            "(P[main|all ok] - P[main|any wrong]) is undefined because no items have incorrect "
            "checks. We report P[main|all checks ok] = overall accuracy as the coupling baseline."
        ),
        "models": {},
        "comparison_B_vs_C": comparison,
    }

    for model_name in all_results:
        output["models"][model_name] = {}
        for cond in ["B", "C"]:
            d = all_results[model_name][cond]
            output["models"][model_name][cond] = {
                "overall_accuracy": d["overall_accuracy"],
                "n_correct": d["n_correct"],
                "n_total": d["n_total"],
                "prompt_level_coupling": d["prompt_level_coupling"],
                "per_family": d["per_family"],
            }

    results_path = os.path.join(PROJ, "results/analysis/coupling_diagnostic.json")
    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    with open(results_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nResults saved to {results_path}")

    fig_path = os.path.join(PROJ, "results/figures/coupling_diagnostic.png")
    plot_coupling_diagnostic(all_results, fig_path)

    fig_path2 = os.path.join(PROJ, "results/figures/coupling_per_family_table.png")
    plot_per_family_coupling_table(all_results, fig_path2)

    print("\n" + "=" * 60)
    print("COUPLING DIAGNOSTIC SUMMARY")
    print("=" * 60)
    for model_name, comp in comparison.items():
        print(f"\n{model_name}:")
        print(f"  P[main correct | all checks correct]:")
        print(f"    B = {comp['accuracy_B']:.1%}")
        print(f"    C = {comp['accuracy_C']:.1%}")
        print(f"  Effective coupling gap (C-B) = {comp['effective_coupling_gap']:+.1%}")
        print(f"  Per-family gaps:")
        for fam, fg in comp["per_family_gaps"].items():
            print(f"    {fam}: B={fg['accuracy_B']:.1%}, C={fg['accuracy_C']:.1%}, "
                  f"gap={fg['gap_C_minus_B']:+.1%}")


if __name__ == "__main__":
    main()
